// Cron notification manager for alerts and notifications
// FEATURE: Multi-channel notification system for cron events

import axios from 'axios';
import {
  CronAlert,
  CronNotificationConfig
} from './cron-types.js';

export class CronNotificationManager {
  private config?: CronNotificationConfig;

  constructor(config?: CronNotificationConfig) {
    this.config = config;
  }

  async sendAlert(alert: CronAlert): Promise<void> {
    if (!this.config?.enabled) {
      return;
    }

    // Check if alert meets notification criteria
    if (!this.shouldNotify(alert)) {
      return;
    }

    const promises: Promise<void>[] = [];

    for (const channel of this.config.channels) {
      switch (channel) {
        case 'console':
          promises.push(this.sendConsoleNotification(alert));
          break;
        case 'email':
          if (this.config.email) {
            promises.push(this.sendEmailNotification(alert));
          }
          break;
        case 'webhook':
          if (this.config.webhook) {
            promises.push(this.sendWebhookNotification(alert));
          }
          break;
        case 'slack':
          if (this.config.slack) {
            promises.push(this.sendSlackNotification(alert));
          }
          break;
      }
    }

    try {
      await Promise.allSettled(promises);
      console.log(`📢 Sent notifications for alert: ${alert.message}`);
    } catch (error) {
      console.error('Failed to send notifications:', error);
    }
  }

  private shouldNotify(alert: CronAlert): boolean {
    if (!this.config?.filters) {
      return true;
    }

    const { filters } = this.config;

    // Check minimum level
    const levelPriority = {
      'info': 1,
      'warning': 2,
      'error': 3,
      'critical': 4
    };

    if (levelPriority[alert.level] < levelPriority[filters.minLevel]) {
      return false;
    }

    // Check keywords filter
    if (filters.keywords?.length) {
      const hasKeyword = filters.keywords.some(keyword =>
        alert.message.toLowerCase().includes(keyword.toLowerCase())
      );
      if (!hasKeyword) {
        return false;
      }
    }

    return true;
  }

  private async sendConsoleNotification(alert: CronAlert): Promise<void> {
    const emoji = this.getLevelEmoji(alert.level);
    const timestamp = new Date(alert.timestamp).toLocaleString();
    
    console.log(`\n${emoji} CRON ALERT [${alert.level.toUpperCase()}] ${timestamp}`);
    console.log(`Job: ${alert.jobName}`);
    console.log(`Message: ${alert.message}`);
    
    if (alert.details) {
      console.log(`Details:`, alert.details);
    }
    
    console.log('---');
  }

  private async sendEmailNotification(alert: CronAlert): Promise<void> {
    // Email implementation would require nodemailer or similar
    // This is a placeholder for the email notification logic
    console.log(`📧 Email notification would be sent for alert: ${alert.message}`);
    
    // Example email content
    const subject = `[LLM-Charge] Cron Alert: ${alert.jobName} - ${alert.level}`;
    const body = `
      Alert Details:
      - Job: ${alert.jobName}
      - Level: ${alert.level}
      - Message: ${alert.message}
      - Timestamp: ${new Date(alert.timestamp).toLocaleString()}
      
      ${alert.details ? `Details: ${JSON.stringify(alert.details, null, 2)}` : ''}
      
      This alert was generated by the LLM-Charge cron system.
    `;
    
    // In a real implementation, you would send the email here
    // using the SMTP configuration from this.config.email
  }

  private async sendWebhookNotification(alert: CronAlert): Promise<void> {
    if (!this.config?.webhook) {
      return;
    }

    const payload = {
      type: 'cron_alert',
      alert: {
        id: alert.id,
        jobId: alert.jobId,
        jobName: alert.jobName,
        level: alert.level,
        message: alert.message,
        details: alert.details,
        timestamp: alert.timestamp
      },
      metadata: {
        source: 'llm-charge-cron',
        version: '1.0.0',
        environment: process.env.NODE_ENV || 'development'
      }
    };

    let retries = 0;
    const maxRetries = this.config.webhook.retries || 3;

    while (retries < maxRetries) {
      try {
        await axios({
          method: 'POST',
          url: this.config.webhook.url,
          headers: {
            'Content-Type': 'application/json',
            ...this.config.webhook.headers
          },
          data: payload,
          timeout: 10000 // 10 second timeout
        });

        console.log(`🔗 Webhook notification sent successfully for alert: ${alert.message}`);
        return;
      } catch (error: any) {
        retries++;
        console.warn(`⚠️ Webhook notification failed (attempt ${retries}/${maxRetries}):`, error.message);
        
        if (retries < maxRetries) {
          // Exponential backoff
          await new Promise(resolve => setTimeout(resolve, Math.pow(2, retries) * 1000));
        }
      }
    }

    console.error(`❌ Failed to send webhook notification after ${maxRetries} attempts`);
  }

  private async sendSlackNotification(alert: CronAlert): Promise<void> {
    if (!this.config?.slack) {
      return;
    }

    const color = this.getSlackColor(alert.level);
    const emoji = this.getLevelEmoji(alert.level);
    
    const payload = {
      channel: this.config.slack.channel,
      username: this.config.slack.username || 'LLM-Charge Cron',
      attachments: [
        {
          color,
          title: `${emoji} Cron Alert: ${alert.jobName}`,
          text: alert.message,
          fields: [
            {
              title: 'Level',
              value: alert.level.toUpperCase(),
              short: true
            },
            {
              title: 'Job ID',
              value: alert.jobId,
              short: true
            },
            {
              title: 'Timestamp',
              value: new Date(alert.timestamp).toLocaleString(),
              short: false
            }
          ],
          footer: 'LLM-Charge Cron System',
          ts: Math.floor(new Date(alert.timestamp).getTime() / 1000)
        }
      ]
    };

    // Add details if available
    if (alert.details) {
      payload.attachments[0].fields.push({
        title: 'Details',
        value: `\`\`\`${JSON.stringify(alert.details, null, 2)}\`\`\``,
        short: false
      } as any);
    }

    try {
      await axios({
        method: 'POST',
        url: this.config.slack.webhookUrl,
        headers: {
          'Content-Type': 'application/json'
        },
        data: payload,
        timeout: 10000
      });

      console.log(`💬 Slack notification sent successfully for alert: ${alert.message}`);
    } catch (error: any) {
      console.error(`❌ Failed to send Slack notification:`, error.message);
    }
  }

  private getLevelEmoji(level: string): string {
    switch (level) {
      case 'info':
        return 'ℹ️';
      case 'warning':
        return '⚠️';
      case 'error':
        return '❌';
      case 'critical':
        return '🚨';
      default:
        return '📢';
    }
  }

  private getSlackColor(level: string): string {
    switch (level) {
      case 'info':
        return '#36a64f'; // Green
      case 'warning':
        return '#ff9900'; // Orange
      case 'error':
        return '#d00000'; // Red
      case 'critical':
        return '#800080'; // Purple
      default:
        return '#cccccc'; // Gray
    }
  }

  updateConfig(config: CronNotificationConfig): void {
    this.config = config;
  }

  getConfig(): CronNotificationConfig | undefined {
    return this.config;
  }
}